name: Running Jmeter tests
on:
  push:
    branches:
      - results-as-csv
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run JMeter Tests
        uses: TimJonsson/PerfAction@v1
        with:
          test-plan-path: jmeter/airportGapTests.jmx
          args: ''
          results-file: results.csv
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results.csv